# This is a basic workflow to help you get started with Actions

name: JEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: customenv
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run tests
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          TOKEN: ${{ secrets.TOKEN }}
        run: npm run test
